name:                 semantic-categorical-oracle
version:              0.1.0.0
visibility:           public
id:                   semantic-categorical-oracle-0.1.0.0-inplace
key:                  semantic-categorical-oracle-0.1.0.0-inplace
license:              BSD-3-Clause
synopsis:             Scoped semantic and categorical oracle
abi:                  inplace
exposed:              True
exposed-modules:      Oracle.Category Oracle.ProofGraph Oracle.Result
import-dirs:
    /home/user/semantic-categorical-oracle/dist-newstyle/build/x86_64-linux/ghc-9.12.4/semantic-categorical-oracle-0.1.0.0/build

library-dirs:
    /home/user/semantic-categorical-oracle/dist-newstyle/build/x86_64-linux/ghc-9.12.4/semantic-categorical-oracle-0.1.0.0/build

library-dirs-static:
    /home/user/semantic-categorical-oracle/dist-newstyle/build/x86_64-linux/ghc-9.12.4/semantic-categorical-oracle-0.1.0.0/build

dynamic-library-dirs:
    /home/user/semantic-categorical-oracle/dist-newstyle/build/x86_64-linux/ghc-9.12.4/semantic-categorical-oracle-0.1.0.0/build

data-dir:             /home/user/semantic-categorical-oracle/.
hs-libraries:         HSsemantic-categorical-oracle-0.1.0.0-inplace
depends:              base-4.21.2.0-60b9
haddock-interfaces:
    /home/user/semantic-categorical-oracle/dist-newstyle/build/x86_64-linux/ghc-9.12.4/semantic-categorical-oracle-0.1.0.0/doc/html/semantic-categorical-oracle/semantic-categorical-oracle.haddock

haddock-html:
    /home/user/semantic-categorical-oracle/dist-newstyle/build/x86_64-linux/ghc-9.12.4/semantic-categorical-oracle-0.1.0.0/doc/html/semantic-categorical-oracle
